version: '3.7'

services:
  consoleserver-apiserver:
    image: consoleserver-apiserver:dev
    container_name: consoleserver-apiserver
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - '8080:8080'
  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - consoleserver-apiserver